### ISSUE TITLE
java.lang.IllegalStateException: The NDI(tm) SDK libraries were not found.

### ISSUE THREAD

**Issue by fabio-anzola** [WalkerKnapp/devolay#13]
Hi,
I'm trying to use this project. Unfortunately I always get the following error:

```
Exception in thread "main" java.lang.ExceptionInInitializerError
	at com.mjppromotions.java.SendVideoExample.main(SendVideoExample.java:15)
Caused by: java.lang.IllegalStateException: The NDI(tm) SDK libraries were not found.
	at com.walker.devolay.Devolay.<clinit>(Devolay.java:36)
	... 1 more

Process finished with exit code 1
```
Line 15, where the error occurs would be this line `Devolay.loadLibraries();`

Can someone help me? What am I doing wrong? 😅

**Comment by WalkerKnapp** [comment]
Hi,
Which platform are you running the library on? Can you check if you have the "NDI_RUNTIME_DIR_V4" environment variable set? I think that for whatever reason the NDI installers on some platforms don't set it automatically. 🤔

**Comment by fabio-anzola** [comment]
Hey,
thanks for your quick reply. 
NDI_RUNTIME_DIR_V4 is not set on my system (Ubuntu Linux 20.04)
What should I set it to?

**Comment by WalkerKnapp** [comment]
Sorry that took so long, I am struggling to get an Ubuntu VM working. I don't have an environment I can test this in right now, but it looks like the normal `InstallNDISDK_v4_Linux.sh` never sets the variable. It should be set to `<where you installed NDI>/NDI SDK for Linux/lib/<your arch>`

**Comment by fabio-anzola** [comment]
Hi, sorry for the late reply. I'm now trying to set up the project on my mac. But the same problem here...
Maybe I'll tell you what I've done. Maybe I missed something.

- Installed the Newtek NDI SDK for Mac/IOS

- Created a new Java project and Included your Library

- Tried to run the SendVideoExample.java file

I have now also tried to set the env variable to the path. Unfortunately no luck.

![Bildschirmfoto 2020-08-20 um 18 55 58](https://user-images.githubusercontent.com/51723533/90802037-f9ebfe80-e316-11ea-8308-945ee6829d7e.png)
![Bildschirmfoto 2020-08-20 um 18 56 59](https://user-images.githubusercontent.com/51723533/90802061-feb0b280-e316-11ea-923e-02d92637be64.png)

**Comment by WalkerKnapp** [comment]
Do you have a development environment set up? If so, could you uncomment lines 60 and 63 of `devolay-natives/src/main/cpp/devolay.cpp` and see what the output is? I'm not sure what would be causing an issue like this.

**Comment by fabio-anzola** [comment]
Unfortunately I'm not really sure how I would go about this.
I right now tried to self-compile your project and see if that helps. Interestingly I get this error/output when executing `./gradlew assemble`:
```
Downloading https://services.gradle.org/distributions-snapshots/gradle-6.4-20200329220053+0000-bin.zip

Exception in thread "main" java.io.FileNotFoundException: https://downloads.gradle-dn.com/distributions-snapshots/gradle-6.4-20200329220053+0000-bin.zip
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1909)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1509)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:245)
	at org.gradle.wrapper.Download.downloadInternal(Download.java:78)
	at org.gradle.wrapper.Download.download(Download.java:63)
	at org.gradle.wrapper.Install$1.call(Install.java:68)
	at org.gradle.wrapper.Install$1.call(Install.java:48)
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:69)
	at org.gradle.wrapper.Install.createDist(Install.java:48)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:107)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:63)
```

**Comment by WalkerKnapp** [comment]
Sorry for the late reply, it looks like gradle decided to pull the snapshot I was using for this. I just pushed a commit that updates the wrapper to the stable `6.6` version.

**Comment by fabio-anzola** [comment]
Hi! I have some very good news!
I just recloned your repo and tried to compile again. This time it worked without an issue!
The jar I compiled now also works flawlessly in my project.
Thank you so much for your time and help! Have a great week!

**Comment by WalkerKnapp** [comment]
Great! I'm in the middle of making some pretty significant changes to how the natives are loaded, so hopefully whatever was causing the original issue won't happen after that.
